### ISSUE TITLE
why two evaluation results are different?

### ISSUE THREAD

**Issue by jojogh** [boostorg/yap#101]
I want to use boost yap to do some small example, the codes are below, why  I put the expression into an operator or member function in a structure, the two evaluation results are different? I am looking forward to your reply, many thanks!
[new4.cpp.txt](https://github.com/boostorg/yap/files/4151862/new4.cpp.txt)

**Comment by jojogh** [comment]
seems no one would answer my question.

**Comment by greole** [comment]
It seems like I experience a similar issue when using stateful  terminals created from rvalue references. I'll have look if I can figure out what is going on...

**Comment by jojogh** [comment]
many thanks

greole <notifications@github.com> 于2020年2月17日周一 上午1:19写道：

**Comment by tzlaine** [comment]
```
struct eval 
{
	auto operator() (double a, double b) {
		auto lhs_w = boost::yap::make_terminal<tarray_expr>(std::move(a));
		auto rhs_w = boost::yap::make_terminal<tarray_expr>(std::move(b));

		return lhs_w + rhs_w;
	}
};
```

This returns a dangling reference to both lhs_w and rhs_w.  The documentation explains why.  If you std::move them both, as in `return std::move(lhs_w) + std::move(rhs_w);`, your code will work as intended.
