### ISSUE TITLE
Bug in test Jamfile

### ISSUE THREAD

**Issue by Flamefire** [boostorg/yap#103]
It seems https://github.com/boostorg/yap/blob/3771507b1d88f883092cbfcff327c688d9488244/test/Jamfile.v2#L8 is wrong.
I tried to copy that for my project but it failed as it can't find `requires in config`.

Apparently `import ../../config/checks/config : requires ;` is the correct one

**Comment by tzlaine** [comment]
This has been cycling for some time in the Boost test runners with no problem.  I'm frankly afraid to touch it.  Do you know of a concrete problem that this fixes?

**Comment by Flamefire** [comment]
Very strange. I tried it and it works for yap. But when I tried it in nowide it did not. It does now so I guess I did something wrong or something has changed. Sorry for the noise, closed.

Main confusion from my side came from the missing CI tests inside this library with b2. If you want: Use boost-ci with AzP. It doesn't interfere with your travis/appveyor tests so you can simply periodically update the yaml file and let boost-ci do the work for you.

**Comment by tzlaine** [comment]
No worries, Jam is hard. :)
