### ISSUE TITLE
constexpr-ify all of algorithm.hpp

### ISSUE THREAD

**Issue by rgrover** [boostorg/yap#79]
it should be possible to call transform on a constexpr expression using a constexpr xform to yield a constexpr value.

**Comment by tzlaine** [comment]
This is true, but too limited.  I need to do a constexpr pass on all the algorithms.  Thanks for pointing this out.

**Comment by tzlaine** [comment]
This is now on develop, as of commit 884e7035cc27657cb60a7801422bcacf79d2f835
