### ISSUE TITLE
replace_placeholders usage

### ISSUE THREAD

**Issue by pkeir** [boostorg/yap#93]
I'd like to use `replace_placeholders`, but I can't manage a call to it without a compilation error. For example with GCC 8.3.0:

```cpp
replace_placeholders( (1_p - 2_p) / 2_p, 3.0, 2.0 );
```

...produces a verbose message including 6 errors (listed below) relating to files within either yap or hana. I'm using yap 1.70 under 64-bit Ubuntu 19.04.

```
error: ‘value’ is not a member of ‘boost::yap::detail::rvalue_mover<true>’
error: ‘value’ is not a member of ‘boost::yap::detail::rvalue_mover<true>’
error: invalid use of void expression
error: ‘void transformed_tuple’ has incomplete type
error: invalid use of void expression
error: ‘void transformed_tuple’ has incomplete type
```

**Comment by pkeir** [comment]
This is fixed by [PR 94](https://github.com/boostorg/yap/pull/94).

**Comment by tzlaine** [comment]
PR applied, thanks again!
